name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ freebsd ]
        goarch: [ amd64, arm64 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version: '1.22'
      - name: Install dependencies
        run: go mod tidy
      - name: Build ${{ matrix.goarch }}
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
        run: go build -ldflags '-s -w --extldflags "-static"' -o panel-${{ matrix.goarch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: panel-${{ matrix.goarch }}
          path: panel-${{ matrix.goarch }}
